# Generated by Django 4.0.5 on 2022-06-05 15:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Members', '0001_initial'),
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseScore',
            fields=[
                ('score_id', models.UUIDField(primary_key=True, serialize=False)),
                ('stars', models.PositiveIntegerField(blank=True, null=True)),
                ('perfects', models.PositiveIntegerField(blank=True, null=True)),
                ('game_point', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1, 'Game point cannot exceed 1.')])),
            ],
        ),
        migrations.CreateModel(
            name='Five01',
            fields=[
                ('basescore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Scores.basescore')),
                ('darts_thrown', models.PositiveIntegerField(blank=True, null=True)),
                ('score_left', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(501, 'Score left cannot exceed 501.')])),
                ('out_thrown', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(170, 'Out cannot exceed 170.')])),
            ],
            bases=('Scores.basescore',),
        ),
        migrations.CreateModel(
            name='Three01',
            fields=[
                ('basescore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Scores.basescore')),
                ('in_thrown', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(170, 'In cannot exceed 170.')])),
                ('out_thrown', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(170, 'Out cannot exceed 170.')])),
            ],
            bases=('Scores.basescore',),
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchPoints', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20, 'Total match points for <django.db.models.fields.related.ForeignKey> cannot be greater than 20. Please review and try again.')])),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Members.team')),
            ],
        ),
        migrations.CreateModel(
            name='Scoreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sub', models.BooleanField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubles_points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)])),
                ('singles_points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)])),
                ('stars', models.PositiveIntegerField(default=0)),
                ('perfects', models.PositiveIntegerField(default=0)),
                ('high_in', models.PositiveIntegerField(blank=True, null=True)),
                ('high_out', models.PositiveIntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homePlayer1_Scoreset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Home1_Scores', to='Scores.scoreset')),
                ('homePlayer2_Scoreset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Home2_Scores', to='Scores.scoreset')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='Schedule.match')),
            ],
        ),
    ]
