# Generated by Django 4.0.5 on 2022-07-03 21:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Members', '0001_initial'),
        ('Schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseScore',
            fields=[
                ('score_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('SNGL', 'Singles'), ('DBLS', 'Doubles')], max_length=4)),
                ('stars', models.PositiveIntegerField(blank=True, null=True)),
                ('perfects', models.PositiveIntegerField(blank=True, null=True)),
                ('game_point', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1, 'Game point cannot exceed 1.')])),
            ],
        ),
        migrations.CreateModel(
            name='Five01',
            fields=[
                ('basescore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Scores.basescore')),
                ('darts_thrown', models.PositiveIntegerField(blank=True, null=True)),
                ('score_left', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(501, 'Score left cannot exceed 501.')])),
                ('out_thrown', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(170, 'Out cannot exceed 170.')])),
            ],
            bases=('Scores.basescore',),
        ),
        migrations.CreateModel(
            name='Three01',
            fields=[
                ('basescore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Scores.basescore')),
                ('in_thrown', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(170, 'In cannot exceed 170.')])),
                ('out_thrown', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(170, 'Out cannot exceed 170.')])),
            ],
            bases=('Scores.basescore',),
        ),
        migrations.CreateModel(
            name='Scoreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sub', models.BooleanField()),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.team')),
            ],
        ),
        migrations.AddField(
            model_name='basescore',
            name='scoreset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scores.scoreset'),
        ),
    ]
