# Generated by Django 4.0.4 on 2022-05-28 13:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Schedule', '0001_initial'),
        ('Scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Schedule.match'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamscore',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Schedule.match'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamscore',
            name='matchPoints',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20, 'Total match points for <django.db.models.fields.related.ForeignKey> cannot be greater than 20. Please review and try again.')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamscore',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Members.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='points_scored1',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(501, 'Points scored exceed 501. Please correct values and try again.')]),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='points_scored2',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(501, 'Points scored exceed 501. Please correct values and try again.')]),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='singles_points',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='points_scored1',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(501, 'Points scored exceed 501. Please correct values and try again.')]),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='points_scored2',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(501, 'Points scored exceed 501. Please correct values and try again.')]),
        ),
    ]
