# Generated by Django 4.2 on 2023-05-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoresummary',
            options={'verbose_name': 'Player Score Summary', 'verbose_name_plural': 'Player Score Summaries'},
        ),
    ]
