# Generated by Django 4.0.5 on 2022-07-04 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Members', '0004_alter_player_options'),
        ('Scores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basescore',
            name='scoreset',
        ),
        migrations.AlterField(
            model_name='basescore',
            name='format',
            field=models.CharField(choices=[('SN', 'Singles'), ('DB', 'Doubles')], max_length=2),
        ),
        migrations.CreateModel(
            name='TeamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_points', models.PositiveIntegerField(null=True)),
                ('best_501', models.PositiveIntegerField(blank=True, null=True)),
                ('darts_thrown', models.PositiveIntegerField()),
                ('score_left', models.PositiveIntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Schedule.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Members.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub', models.BooleanField(verbose_name='Subs')),
                ('stars', models.PositiveIntegerField(blank=True, null=True)),
                ('perfects', models.PositiveIntegerField(blank=True, null=True)),
                ('singles_points', models.PositiveIntegerField(blank=True, null=True)),
                ('doubles_points', models.PositiveIntegerField(blank=True, null=True)),
                ('match_points', models.PositiveIntegerField(null=True)),
                ('high_in', models.PositiveIntegerField(blank=True, null=True)),
                ('high_out', models.PositiveIntegerField(blank=True, null=True)),
                ('best_501', models.PositiveIntegerField(blank=True, null=True)),
                ('darts_thrown', models.PositiveIntegerField()),
                ('score_left', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Schedule.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Members.team')),
            ],
        ),
    ]
