# Generated by Django 4.0.5 on 2022-06-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchplay',
            name='homePlayer1_Scoreset',
        ),
        migrations.RemoveField(
            model_name='matchplay',
            name='homePlayer2_Scoreset',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='doubles_points',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='high_in',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='high_out',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='perfects',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='singles_points',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='stars',
        ),
        migrations.AddField(
            model_name='scoreset',
            name='cricket_doubles',
            field=models.ManyToManyField(related_name='cricket_doubles', to='Scores.basescore'),
        ),
        migrations.AddField(
            model_name='scoreset',
            name='cricket_singles',
            field=models.ManyToManyField(related_name='cricket_singles', to='Scores.basescore'),
        ),
        migrations.AddField(
            model_name='scoreset',
            name='five01_doubles',
            field=models.ManyToManyField(related_name='five01_doubles', to='Scores.five01'),
        ),
        migrations.AddField(
            model_name='scoreset',
            name='five01_singles',
            field=models.ManyToManyField(related_name='five01_singles', to='Scores.five01'),
        ),
        migrations.AddField(
            model_name='scoreset',
            name='three01_doubles',
            field=models.ManyToManyField(to='Scores.three01'),
        ),
    ]
