# Generated by Django 4.2 on 2023-05-22 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Schedule", "0003_rename_scheduler_schedulerule_and_more"),
        ("Scores", "0002_alter_scoresummary_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scoredetail",
            options={
                "verbose_name": "Score Detail",
                "verbose_name_plural": "Score Details",
            },
        ),
        migrations.AlterModelOptions(
            name="teamscoresummary",
            options={
                "verbose_name": "Team Score Summary",
                "verbose_name_plural": "Team Score Summaries",
            },
        ),
        migrations.AlterField(
            model_name="scoredetail",
            name="score_summary",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Scores.scoresummary",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scoredetail",
            unique_together={("match", "player")},
        ),
    ]
