# Generated by Django 4.0.5 on 2022-06-05 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_initial'),
        ('Schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Scores', '0002_remove_matchplay_homeplayer1_scoreset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerScoreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sub', models.BooleanField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.team')),
            ],
        ),
        migrations.RemoveField(
            model_name='matchplay',
            name='match',
        ),
        migrations.DeleteModel(
            name='PlayerStats',
        ),
        migrations.RemoveField(
            model_name='scoreset',
            name='cricket_doubles',
        ),
        migrations.RemoveField(
            model_name='scoreset',
            name='cricket_singles',
        ),
        migrations.RemoveField(
            model_name='scoreset',
            name='five01_doubles',
        ),
        migrations.RemoveField(
            model_name='scoreset',
            name='five01_singles',
        ),
        migrations.RemoveField(
            model_name='scoreset',
            name='player',
        ),
        migrations.RemoveField(
            model_name='scoreset',
            name='team',
        ),
        migrations.RemoveField(
            model_name='scoreset',
            name='three01_doubles',
        ),
        migrations.RemoveField(
            model_name='teamstats',
            name='team',
        ),
        migrations.AddField(
            model_name='basescore',
            name='format',
            field=models.CharField(choices=[('SNGL', 'Singles'), ('DBLS', 'Doubles')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MatchPlay',
        ),
        migrations.DeleteModel(
            name='Scoreset',
        ),
        migrations.DeleteModel(
            name='TeamStats',
        ),
        migrations.AddField(
            model_name='basescore',
            name='scoreset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Scores.playerscoreset'),
            preserve_default=False,
        ),
    ]
