# Generated by Django 4.2 on 2023-08-28 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Schedule", "0003_rename_scheduler_schedulerule_and_more"),
        ("Members", "0006_alter_player_options"),
        ("Scores", "0003_alter_scoredetail_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forfeit",
            options={"verbose_name": "Forfeit", "verbose_name_plural": "Forfeits"},
        ),
        migrations.AlterModelOptions(
            name="scoresummary",
            options={
                "verbose_name": "Score Summary",
                "verbose_name_plural": "Score Summaries",
            },
        ),
        migrations.AlterUniqueTogether(
            name="forfeit",
            unique_together={("match", "team")},
        ),
    ]
