# Generated by Django 4.0.5 on 2022-06-05 21:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Schedule', '0001_initial'),
        ('Members', '0002_initial'),
        ('Scores', '0003_playerscoreset_remove_matchplay_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basescore',
            name='game_point',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1, 'Game point cannot exceed 1.')]),
        ),
        migrations.AlterField(
            model_name='basescore',
            name='score_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Scoreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sub', models.BooleanField()),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.team')),
            ],
        ),
        migrations.AlterField(
            model_name='basescore',
            name='scoreset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scores.scoreset'),
        ),
        migrations.DeleteModel(
            name='PlayerScoreset',
        ),
    ]
