# Generated by Django 4.2 on 2023-07-07 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Scores", "0003_alter_scoredetail_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scoresummary",
            options={
                "verbose_name": "Score Summary",
                "verbose_name_plural": "Score Summaries",
            },
        ),
    ]
