# Generated by Django 4.0.5 on 2022-08-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scores', '0004_gamescore_remove_five01_scoreset_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoreset',
            options={},
        ),
        migrations.RemoveField(
            model_name='scoreset',
            name='created',
        ),
        migrations.RemoveField(
            model_name='scoreset',
            name='modified',
        ),
    ]
