# Generated by Django 4.2 on 2023-07-02 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Scores", "0004_alter_scoresummary_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamscoresummary",
            name="darts_thrown1",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(50)],
            ),
        ),
    ]
