# Generated by Django 4.2 on 2023-09-23 02:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Members", "0013_remove_registration_created_by_and_more"),
        ("Schedule", "0004_alter_scheduleweek_options_and_more"),
        ("Scores", "0005_alter_teamscoresummary_darts_thrown1"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forfeit",
            options={"verbose_name": "Forfeit", "verbose_name_plural": "Forfeits"},
        ),
        migrations.AlterUniqueTogether(
            name="forfeit",
            unique_together={("match", "team")},
        ),
    ]
