# Generated by Django 4.1 on 2022-08-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Scores", "0005_alter_scoreset_options_remove_scoreset_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scoreset",
            name="match",
        ),
    ]
