# Generated by Django 4.1 on 2022-08-28 17:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("Schedule", "0007_remove_match_scoresets"),
        ("Scores", "0006_remove_scoreset_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoreset",
            name="match",
            field=models.ForeignKey(
                default=uuid.UUID("c0d21b38-5d63-4500-a16c-e37cf1c56ecd"),
                on_delete=django.db.models.deletion.CASCADE,
                to="Schedule.match",
            ),
            preserve_default=False,
        ),
    ]
