# Generated by Django 4.2 on 2023-09-25 05:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Scores", "0004_alter_forfeit_options_alter_scoresummary_options_and_more"),
        ("Scores", "0006_alter_forfeit_options_alter_forfeit_unique_together"),
    ]

    operations = []
