# Generated by Django 4.2 on 2023-09-28 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Scores", "0007_merge_20230925_0139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamscoresummary",
            name="darts_thrown2",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(50)],
            ),
        ),
    ]
