# Generated by Django 4.1 on 2022-09-02 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Schedule", "0007_remove_match_scoresets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Scores", "0007_scoreset_match"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="scoreset",
            unique_together={("match", "player")},
        ),
    ]
