# Generated by Django 4.2.6 on 2023-12-06 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Members", "0015_alter_player_managers"),
        ("Scores", "0008_alter_teamscoresummary_darts_thrown2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forfeit",
            name="team",
            field=models.ForeignKey(
                limit_choices_to={"match__awayTeam": "team", "match__homeTeam": "team"},
                on_delete=django.db.models.deletion.CASCADE,
                to="Members.team",
            ),
        ),
    ]
