# Generated by Django 4.2.7 on 2024-01-30 14:41

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Scores", "0009_alter_forfeit_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoredetail",
            name="team_score_summary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Scores.teamscoresummary",
            ),
        ),
        migrations.AlterField(
            model_name="scoredetail",
            name="darts_thrown_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(
                    verbose_name=django.core.validators.MaxValueValidator(50)
                ),
                blank=True,
                max_length=4,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="scoredetail",
            name="out_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(
                    verbose_name=django.core.validators.MaxValueValidator(170)
                ),
                blank=True,
                max_length=6,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="scoredetail",
            name="score_left_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(
                    verbose_name=django.core.validators.MaxValueValidator(501)
                ),
                blank=True,
                max_length=4,
                null=True,
                size=None,
            ),
        ),
    ]
