# Generated by Django 4.1.5 on 2023-01-13 14:11

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0013_rename_participating_divisions_season_divisions'),
        ('Members', '0012_alter_player_phonenumber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Scores', '0009_scoreset_created_scoreset_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_stars', models.IntegerField(blank=True, null=True)),
                ('total_perfects', models.IntegerField(blank=True, null=True)),
                ('total_points', models.IntegerField(default=0)),
                ('high_in', models.IntegerField(blank=True, null=True)),
                ('high_out', models.IntegerField(blank=True, null=True)),
                ('darts_thrown1', models.IntegerField(blank=True, null=True)),
                ('score_left1', models.IntegerField(blank=True, null=True)),
                ('darts_thrown2', models.IntegerField(blank=True, null=True)),
                ('score_left2', models.IntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.team')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stars_list', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, max_length=10, null=True, size=None)),
                ('perfects_list', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, max_length=10, null=True, size=None)),
                ('points_list', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(verbose_name=django.core.validators.MaxValueValidator(1)), blank=True, max_length=10, null=True, size=None)),
                ('darts_thrown_list', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(verbose_name=django.core.validators.MaxValueValidator(50)), blank=True, max_length=2, null=True, size=None)),
                ('score_left_list', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(verbose_name=django.core.validators.MaxValueValidator(501)), blank=True, max_length=2, null=True, size=None)),
                ('in_list', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(verbose_name=django.core.validators.MaxValueValidator(170)), blank=True, max_length=2, null=True, size=None)),
                ('out_list', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(verbose_name=django.core.validators.MaxValueValidator(170)), blank=True, max_length=4, null=True, size=None)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('score_summary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Scores.scoresummary')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.team')),
            ],
        ),
        migrations.CreateModel(
            name='Forfeit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.team')),
            ],
        ),
    ]
