# Generated by Django 4.1.5 on 2023-01-14 04:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Members', '0012_alter_player_phonenumber'),
        ('Schedule', '0013_rename_participating_divisions_season_divisions'),
        ('Scores', '0010_scoresummary_scoredetail_forfeit'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresummary',
            name='doubles_points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='scoresummary',
            name='singles_points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterUniqueTogether(
            name='scoresummary',
            unique_together={('match', 'player')},
        ),
        migrations.RemoveField(
            model_name='scoresummary',
            name='total_points',
        ),
        migrations.CreateModel(
            name='TeamScoreSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('darts_thrown1', models.IntegerField(blank=True, null=True)),
                ('score_left1', models.IntegerField(blank=True, null=True)),
                ('darts_thrown2', models.IntegerField(blank=True, null=True)),
                ('score_left2', models.IntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.team')),
            ],
            options={
                'unique_together': {('match', 'team')},
            },
        ),
    ]
