# Generated by Django 4.1.5 on 2023-02-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scores', '0013_alter_scoredetail_options_scoredetail_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoresummary',
            options={'verbose_name_plural': 'Player Score Summaries'},
        ),
        migrations.AlterModelOptions(
            name='teamscoresummary',
            options={'verbose_name_plural': 'Team Score Summaries'},
        ),
        migrations.AddField(
            model_name='scoresummary',
            name='is_sub',
            field=models.BooleanField(default=False),
        ),
    ]
