# Generated by Django 4.0.5 on 2022-06-05 15:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Locations', '0001_initial'),
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonNum', models.PositiveIntegerField(verbose_name='Season Number')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('playoffFinalsDate', models.DateTimeField(verbose_name='Playoff Finals')),
                ('playoffFinalsLocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Locations.establishment')),
            ],
            options={
                'ordering': ['-seasonNum'],
                'get_latest_by': ['startDate'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekNum', models.IntegerField(blank=True, null=True)),
                ('matchDate', models.DateField(blank=True, null=True)),
                ('awayTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayMatches', to='Members.team')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Locations.division')),
                ('homeTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeMatches', to='Members.team')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
