# Generated by Django 4.2 on 2023-05-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0003_alter_division_matchnight_and_more'),
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleweek',
            options={},
        ),
        migrations.AlterField(
            model_name='scheduleweek',
            name='week_number',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='divisions',
            field=models.ManyToManyField(db_index=True, to='Locations.division'),
        ),
        migrations.AlterField(
            model_name='season',
            name='match_play_end_dt',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='match_play_start_dt',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_number',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Season Number'),
        ),
    ]
