# Generated by Django 4.2 on 2023-05-21 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Locations", "0004_alter_division_matchnight"),
        ("Schedule", "0002_alter_scheduleweek_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="boards",
        ),
        migrations.AlterField(
            model_name="season",
            name="match_play_end_dt",
            field=models.DateField(db_index=True, verbose_name="Match Play End Date"),
        ),
        migrations.AlterField(
            model_name="season",
            name="match_play_start_dt",
            field=models.DateField(db_index=True, verbose_name="Match Play Start Date"),
        ),
        migrations.AlterField(
            model_name="season",
            name="playoffFinalsLocation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Locations.establishment",
                verbose_name="Playoff Finals Location",
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="playoff_finals_dt",
            field=models.DateTimeField(verbose_name="Playoff Finals Date"),
        ),
    ]
