# Generated by Django 4.0.5 on 2022-07-17 23:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0002_remove_match_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='boards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True, null=True), blank=True, null=True, size=2),
        ),
    ]
