# Generated by Django 4.0.5 on 2022-06-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0002_match_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='boards',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
