# Generated by Django 4.1 on 2022-08-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scores", "0006_remove_scoreset_match"),
        ("Schedule", "0003_match_boards"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="scores",
            field=models.ManyToManyField(to="Scores.scoreset"),
        ),
    ]
