# Generated by Django 4.0.5 on 2022-06-10 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Schedule', '0003_match_boards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('body', models.CharField(max_length=1000)),
                ('active_date', models.DateTimeField()),
                ('inactive_date', models.DateTimeField()),
                ('date_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Schedule.season')),
            ],
        ),
    ]
