# Generated by Django 4.2 on 2023-09-15 03:48

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):
    dependencies = [
        ("Locations", "0005_establishment_numberofboards"),
        ("Schedule", "0003_rename_scheduler_schedulerule_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scheduleweek",
            options={"ordering": ["-season", "division", "week_number"]},
        ),
        migrations.AlterField(
            model_name="scheduleweek",
            name="division",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                chained_field="season",
                chained_model_field="season",
                on_delete=django.db.models.deletion.CASCADE,
                to="Locations.division",
            ),
        ),
    ]
