# Generated by Django 4.0.5 on 2022-06-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0004_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=models.TextField(),
        ),
    ]
