# Generated by Django 4.2.7 on 2024-01-16 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Members", "0015_alter_player_managers"),
        ("Schedule", "0004_alter_scheduleweek_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[("S", "Scheduled"), ("P", "Played"), ("F", "Forfeit")],
                default="S",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="awayTeam",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="awayMatches",
                to="Members.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="homeTeam",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homeMatches",
                to="Members.team",
            ),
        ),
    ]
