# Generated by Django 4.1 on 2022-08-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scores", "0006_remove_scoreset_match"),
        ("Schedule", "0004_match_scores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="scores",
            field=models.ManyToManyField(blank=True, to="Scores.scoreset"),
        ),
    ]
