# Generated by Django 4.2.7 on 2024-01-30 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Locations", "0006_rename_divisionmanager_division_division_manager"),
        ("Schedule", "0005_match_status_alter_match_awayteam_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="scheduleweek",
            unique_together={("season", "division", "match_date", "week_number")},
        ),
    ]
