# Generated by Django 4.1 on 2022-08-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Schedule", "0005_alter_match_scores"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="scores",
            new_name="scoresets",
        ),
    ]
