# Generated by Django 4.1 on 2022-08-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Schedule", "0006_rename_scores_match_scoresets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="scoresets",
        ),
    ]
