# Generated by Django 5.0 on 2024-12-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Schedule", "0006_alter_scheduleweek_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="awayBye",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="homeBye",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("S", "Scheduled"),
                    ("P", "Played"),
                    ("F", "Forfeit"),
                    ("B", "Bye"),
                ],
                default="S",
                max_length=1,
            ),
        ),
    ]
