# Generated by Django 5.0 on 2024-12-11 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Members", "0015_alter_player_managers"),
        ("Schedule", "0007_match_awaybye_match_homebye_alter_match_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="awayTeam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="awayMatches",
                to="Members.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="homeTeam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homeMatches",
                to="Members.team",
            ),
        ),
    ]
