# Generated by Django 4.1 on 2022-09-12 18:29

from django.db import migrations, models
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ("Schedule", "0007_remove_match_scoresets"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recurrence", recurrence.fields.RecurrenceField()),
            ],
        ),
    ]
