# Generated by Django 4.1 on 2022-09-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Schedule", "0008_recurringevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringevent",
            name="title",
            field=models.CharField(default="Title", max_length=48),
            preserve_default=False,
        ),
    ]
