# Generated by Django 4.1 on 2022-09-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Schedule", "0009_recurringevent_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringevent",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
