# Generated by Django 4.1 on 2022-11-23 18:28

from django.db import migrations, models
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ("Schedule", "0010_recurringevent_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scheduler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=48)),
                ("description", models.TextField(blank=True, null=True)),
                ("frequency", recurrence.fields.RecurrenceField()),
            ],
        ),
        migrations.DeleteModel(
            name="RecurringEvent",
        ),
        migrations.AlterModelOptions(
            name="season",
            options={
                "get_latest_by": ["match_play_start_dt"],
                "ordering": ["-season_number"],
            },
        ),
        migrations.RenameField(
            model_name="season",
            old_name="endDate",
            new_name="match_play_end_dt",
        ),
        migrations.RenameField(
            model_name="season",
            old_name="startDate",
            new_name="match_play_start_dt",
        ),
        migrations.RenameField(
            model_name="season",
            old_name="playoffFinalsDate",
            new_name="playoff_finals_dt",
        ),
        migrations.RenameField(
            model_name="season",
            old_name="seasonNum",
            new_name="season_number",
        ),
    ]
