# Generated by Django 4.1.5 on 2023-01-10 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Locations', '0007_remove_division_season'),
        ('Schedule', '0011_scheduler_delete_recurringevent_alter_season_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='season',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='title_slug',
        ),
        migrations.AddField(
            model_name='announcement',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='season',
            name='participating_divisions',
            field=models.ManyToManyField(to='Locations.division'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
