# Generated by Django 4.1.5 on 2023-01-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0012_remove_announcement_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='participating_divisions',
            new_name='divisions',
        ),
    ]
