# Generated by Django 4.1.5 on 2023-02-04 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0013_alter_division_matchnight'),
        ('Schedule', '0013_rename_participating_divisions_season_divisions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='division',
        ),
        migrations.RemoveField(
            model_name='match',
            name='matchDate',
        ),
        migrations.RemoveField(
            model_name='match',
            name='season',
        ),
        migrations.RemoveField(
            model_name='match',
            name='weekNum',
        ),
        migrations.CreateModel(
            name='ScheduleWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('match_date', models.DateField()),
                ('playoff_week', models.BooleanField(default=False)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Locations.division')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.season')),
            ],
            options={
                'ordering': ['season', 'division', 'week_number'],
                'unique_together': {('season', 'week_number', 'division')},
            },
        ),
        migrations.AddField(
            model_name='match',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Schedule.scheduleweek'),
        ),
    ]
