# Generated by Django 4.0.4 on 2022-05-27 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Locations', '0001_initial'),
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.season'),
        ),
    ]
