# Generated by Django 4.2 on 2023-05-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='matchNight',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], db_index=True, max_length=9, null=True, verbose_name='Match Night'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
