# Generated by Django 4.0.5 on 2022-07-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Locations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="establishment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
