# Generated by Django 4.0.5 on 2022-07-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0003_establishment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='is_active',
            field=models.BooleanField(verbose_name='Set Active?'),
        ),
    ]
