# Generated by Django 4.2 on 2023-05-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0003_alter_division_matchnight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='matchNight',
            field=models.CharField(blank=True, choices=[('Mon', 'Mon'), ('Tues', 'Tues'), ('Wed', 'Wed'), ('Thurs', 'Thurs'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], db_index=True, max_length=9, null=True, verbose_name='Match Night'),
        ),
    ]
