# Generated by Django 4.0.5 on 2022-08-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Locations", "0004_alter_division_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="division",
            name="is_active",
        ),
    ]
