# Generated by Django 4.2 on 2023-06-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Locations", "0004_alter_division_matchnight"),
    ]

    operations = [
        migrations.AddField(
            model_name="establishment",
            name="numberOfBoards",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
