# Generated by Django 4.2 on 2023-10-14 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Locations", "0005_establishment_numberofboards"),
    ]

    operations = [
        migrations.RenameField(
            model_name="division",
            old_name="divisionManager",
            new_name="division_manager",
        ),
    ]
