# Generated by Django 4.1 on 2022-09-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Schedule", "0010_recurringevent_description"),
        ("Locations", "0005_remove_division_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="division",
            name="season",
        ),
        migrations.AddField(
            model_name="division",
            name="season",
            field=models.ManyToManyField(to="Schedule.season"),
        ),
    ]
