# Generated by Django 4.1.5 on 2023-01-10 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0006_remove_division_season_division_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='season',
        ),
    ]
