# Generated by Django 4.1.5 on 2023-01-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0007_remove_division_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['area__number', 'matchNight']},
        ),
    ]
