# Generated by Django 4.1.5 on 2023-01-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0008_alter_division_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='shortName',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
