# Generated by Django 4.1.5 on 2023-01-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0009_establishment_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='matchNight',
            field=models.CharField(blank=True, choices=[('Monday', 'Mon'), ('Tuesday', 'Tues'), ('Wednesday', 'Wed'), ('Thursday', 'Thurs'), ('Friday', 'Fri'), ('Satday', 'Sat'), ('Sunday', 'Sun')], max_length=9, null=True, verbose_name='Match Night'),
        ),
    ]
