# Generated by Django 4.1.5 on 2023-01-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0011_alter_division_matchnight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='matchNight',
            field=models.CharField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=9, null=True, verbose_name='Match Night'),
        ),
    ]
