# Generated by Django 4.1.5 on 2023-01-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0012_alter_division_matchnight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='matchNight',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9, null=True, verbose_name='Match Night'),
        ),
    ]
