# Generated by Django 4.0.5 on 2022-07-03 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Members", "0001_initial"),
        ("Schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Schedule.season"
            ),
        ),
    ]
