# Generated by Django 4.2 on 2023-04-24 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Members', '0001_initial'),
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.season'),
        ),
    ]
