# Generated by Django 4.0.5 on 2022-07-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"verbose_name": "Player", "verbose_name_plural": "Players"},
        ),
    ]
