# Generated by Django 4.2 on 2023-05-11 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Members", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="players",
            field=models.ManyToManyField(
                db_index=True,
                max_length=2,
                related_name="teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
