# Generated by Django 4.0.5 on 2022-06-12 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Members', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.AddField(
            model_name='team',
            name='player1',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='team_member_1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='player2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_member_2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
