# Generated by Django 4.2 on 2023-05-13 23:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("Members", "0003_alter_team_players"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="team",
            managers=[
                ("details", django.db.models.manager.Manager()),
            ],
        ),
    ]
