# Generated by Django 4.0.5 on 2022-07-03 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0003_alter_player_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'player', 'verbose_name_plural': 'players'},
        ),
    ]
