# Generated by Django 4.2 on 2023-05-21 02:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Members", "0004_alter_team_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="team",
            managers=[],
        ),
    ]
