# Generated by Django 4.0.5 on 2022-08-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0005_playerseasoninstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerseasoninstance',
            name='partner',
        ),
        migrations.AddField(
            model_name='playerseasoninstance',
            name='matches_played',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
