# Generated by Django 4.2 on 2023-06-20 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Members", "0005_alter_team_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={
                "ordering": ["first_name", "last_name", "username"],
                "verbose_name": "player",
                "verbose_name_plural": "players",
            },
        ),
    ]
