# Generated by Django 4.2 on 2023-07-02 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import smart_selects.db_fields


class Migration(migrations.Migration):
    replaces = [
        (
            "Members",
            "0007_remove_team_division_remove_team_season_registration_and_more",
        ),
        ("Members", "0008_alter_registration_options_registration_created_and_more"),
        ("Members", "0009_alter_registration_options_registration_created_by_and_more"),
        ("Members", "0010_alter_registration_division_and_more"),
        ("Members", "0011_alter_registration_unique_together"),
    ]

    dependencies = [
        ("Members", "0006_alter_player_options"),
        ("Locations", "0005_establishment_numberofboards"),
        ("Schedule", "0003_rename_scheduler_schedulerule_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="division",
        ),
        migrations.RemoveField(
            model_name="team",
            name="season",
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "division",
                    smart_selects.db_fields.ChainedForeignKey(
                        auto_choose=True,
                        chained_field="season",
                        chained_model_field="season",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Locations.division",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Schedule.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Members.team"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True,
                        default=django.utils.timezone.now,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registrations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registrations_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-season", "division", "team"],
                "verbose_name": "Team Registration",
                "verbose_name_plural": "Team Registrations",
                "unique_together": {("season", "team")},
            },
        ),
        migrations.AddField(
            model_name="team",
            name="division",
            field=models.ManyToManyField(
                through="Members.Registration", to="Locations.division"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="season",
            field=models.ManyToManyField(
                through="Members.Registration", to="Schedule.season"
            ),
        ),
    ]
