# Generated by Django 4.0.5 on 2022-08-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0006_remove_playerseasoninstance_partner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerseasoninstance",
            name="doubles_wins",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerseasoninstance",
            name="singles_wins",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
