# Generated by Django 4.2 on 2023-09-28 13:42

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import smart_selects.db_fields


class Migration(migrations.Migration):
    dependencies = [
        ("Schedule", "0003_rename_scheduler_schedulerule_and_more"),
        ("Locations", "0005_establishment_numberofboards"),
        ("Members", "0006_alter_player_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="division",
        ),
        migrations.RemoveField(
            model_name="team",
            name="season",
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "division",
                    smart_selects.db_fields.ChainedForeignKey(
                        auto_choose=True,
                        chained_field="season",
                        chained_model_field="season",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Locations.division",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Schedule.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="Members.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Registration",
                "verbose_name_plural": "Team Registrations",
                "ordering": ["-season", "division", "team"],
                "unique_together": {("season", "team")},
            },
        ),
        migrations.AddField(
            model_name="team",
            name="division",
            field=smart_selects.db_fields.ChainedManyToManyField(
                chained_field="season",
                chained_model_field="divisions",
                through="Members.Registration",
                to="Locations.division",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="season",
            field=models.ManyToManyField(
                through="Members.Registration", to="Schedule.season"
            ),
        ),
    ]
