# Generated by Django 4.0.5 on 2022-08-14 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0007_playerseasoninstance_doubles_wins_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerSeasonInstance',
        ),
    ]
