# Generated by Django 4.1 on 2022-09-02 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0008_delete_playerseasoninstance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="player1",
        ),
        migrations.RemoveField(
            model_name="team",
            name="player2",
        ),
        migrations.AddField(
            model_name="team",
            name="players",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
