# Generated by Django 4.1 on 2022-09-22 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0009_remove_team_player1_remove_team_player2_team_players"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="players",
        ),
        migrations.AddField(
            model_name="team",
            name="player1",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_member_1",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="player2",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_member_2",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
