# Generated by Django 4.1 on 2022-11-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Schedule",
            "0011_scheduler_delete_recurringevent_alter_season_options_and_more",
        ),
        ("Members", "0010_remove_team_players_team_player1_team_player2"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("player1", "season"), ("player2", "season")},
        ),
    ]
