# Generated by Django 4.1.5 on 2023-01-10 05:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0011_alter_team_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number'),
        ),
    ]
