# Generated by Django 4.2 on 2023-07-02 21:22

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "Members",
            "0007_remove_team_division_remove_team_season_registration_and_more_squashed_0011_alter_registration_unique_together",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, verbose_name="created"
            ),
        ),
    ]
