# Generated by Django 4.2 on 2023-09-22 13:04

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):
    dependencies = [
        ("Locations", "0005_establishment_numberofboards"),
        ("Members", "0012_alter_registration_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="modified_by",
        ),
        migrations.AlterField(
            model_name="registration",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="Members.team",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="division",
            field=smart_selects.db_fields.ChainedManyToManyField(
                chained_field="season",
                chained_model_field="divisions",
                through="Members.Registration",
                to="Locations.division",
            ),
        ),
    ]
