# Generated by Django 4.2.6 on 2023-10-22 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Members", "0013_remove_registration_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="player",
            managers=[],
        ),
    ]
