# Generated by Django 4.2.6 on 2023-10-22 12:00

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Members", "0014_alter_player_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="player",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
