name: Test

on:
  pull_request:
    branches: [ "prod" ]
jobs:
    test-report:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: codecov/codecov-action@main
              with:
                verbose: true # optional (default = false)
              env:
                token: ${{ secrets.CODECOV_TOKEN }}